import type { JobType } from "./types"

export const jobsData: JobType[] = [
  {
    id: "1",
    title: "Senior Frontend Developer",
    companyName: "TechCorp",
    companyLogo: "/placeholder.svg?height=48&width=48",
    location: "Remote (Worldwide)",
    jobType: "Full-time",
    salary: "$90,000 - $120,000",
    experience: "3-5 years",
    description:
      "We're looking for a Senior Frontend Developer to join our team. You'll be responsible for building user interfaces for our web applications using React and Next.js.",
    responsibilities: [
      "Develop and maintain responsive web applications using React and Next.js",
      "Collaborate with designers to implement UI/UX designs",
      "Write clean, maintainable, and efficient code",
      "Optimize applications for maximum speed and scalability",
      "Participate in code reviews and mentor junior developers",
    ],
    requirements: [
      "3+ years of experience with React",
      "Experience with Next.js and TypeScript",
      "Strong understanding of web fundamentals (HTML, CSS, JavaScript)",
      "Experience with state management libraries (Redux, Zustand, etc.)",
      "Knowledge of responsive design and cross-browser compatibility",
    ],
    benefits: [
      "Competitive salary and equity",
      "Flexible working hours",
      "Remote-first culture",
      "Health insurance",
      "Professional development budget",
    ],
    skills: ["React", "Next.js", "TypeScript", "Tailwind CSS", "Redux"],
    postedDate: "2 days ago",
    companyDescription:
      "TechCorp is a leading technology company specializing in web and mobile application development.",
    companyWebsite: "techcorp.com",
    companyIndustry: "Software Development",
    companySize: "50-100 employees",
  },
  {
    id: "2",
    title: "Full Stack Developer",
    companyName: "InnovateSoft",
    companyLogo: "/placeholder.svg?height=48&width=48",
    location: "Remote (US Only)",
    jobType: "Full-time",
    salary: "$100,000 - $130,000",
    experience: "4-6 years",
    description:
      "We are seeking a Full Stack Developer to join our growing team. You will be responsible for developing and maintaining web applications using modern technologies.",
    responsibilities: [
      "Design and develop web applications using React, Node.js, and PostgreSQL",
      "Implement RESTful APIs and GraphQL endpoints",
      "Optimize database queries and application performance",
      "Collaborate with product managers and designers",
      "Participate in agile development processes",
    ],
    requirements: [
      "4+ years of experience in full stack development",
      "Strong proficiency in JavaScript/TypeScript",
      "Experience with React, Node.js, and SQL databases",
      "Knowledge of cloud services (AWS, GCP, or Azure)",
      "Understanding of CI/CD pipelines",
    ],
    benefits: [
      "Competitive compensation package",
      "Remote work flexibility",
      "Health, dental, and vision insurance",
      "401(k) matching",
      "Unlimited PTO",
    ],
    skills: ["React", "Node.js", "PostgreSQL", "TypeScript", "AWS"],
    postedDate: "1 week ago",
    companyDescription: "InnovateSoft builds cutting-edge software solutions for businesses of all sizes.",
    companyWebsite: "innovatesoft.io",
    companyIndustry: "Software Development",
    companySize: "100-250 employees",
  },
  {
    id: "3",
    title: "UX/UI Designer",
    companyName: "DesignHub",
    companyLogo: "/placeholder.svg?height=48&width=48",
    location: "Remote (Europe)",
    jobType: "Full-time",
    salary: "$70,000 - $90,000",
    experience: "2-4 years",
    description:
      "We're looking for a talented UX/UI Designer to create amazing user experiences. You'll work on designing interfaces for web and mobile applications.",
    responsibilities: [
      "Create wireframes, prototypes, and high-fidelity designs",
      "Conduct user research and usability testing",
      "Collaborate with developers to implement designs",
      "Create and maintain design systems",
      "Stay up-to-date with design trends and best practices",
    ],
    requirements: [
      "2+ years of experience in UX/UI design",
      "Proficiency in design tools (Figma, Sketch, Adobe XD)",
      "Portfolio demonstrating strong design skills",
      "Understanding of user-centered design principles",
      "Experience working in agile environments",
    ],
    benefits: [
      "Competitive salary",
      "Flexible working hours",
      "Remote work",
      "Health benefits",
      "Professional development opportunities",
    ],
    skills: ["UI Design", "UX Design", "Figma", "Wireframing", "Prototyping"],
    postedDate: "3 days ago",
    companyDescription: "DesignHub is a creative agency specializing in digital product design and branding.",
    companyWebsite: "designhub.co",
    companyIndustry: "Design",
    companySize: "20-50 employees",
  },
  {
    id: "4",
    title: "DevOps Engineer",
    companyName: "CloudTech",
    companyLogo: "/placeholder.svg?height=48&width=48",
    location: "Remote (Worldwide)",
    jobType: "Full-time",
    salary: "$110,000 - $140,000",
    experience: "3-5 years",
    description:
      "We are looking for a DevOps Engineer to help us build and maintain our cloud infrastructure. You'll be responsible for automating deployment processes and ensuring system reliability.",
    responsibilities: [
      "Design and implement CI/CD pipelines",
      "Manage cloud infrastructure using Infrastructure as Code",
      "Monitor system performance and troubleshoot issues",
      "Implement security best practices",
      "Collaborate with development teams to improve deployment processes",
    ],
    requirements: [
      "3+ years of experience in DevOps or SRE roles",
      "Experience with cloud platforms (AWS, GCP, or Azure)",
      "Knowledge of containerization (Docker, Kubernetes)",
      "Experience with Infrastructure as Code (Terraform, CloudFormation)",
      "Strong scripting skills (Bash, Python)",
    ],
    benefits: [
      "Competitive salary",
      "Remote work",
      "Health insurance",
      "401(k) matching",
      "Professional development budget",
    ],
    skills: ["AWS", "Docker", "Kubernetes", "Terraform", "CI/CD"],
    postedDate: "5 days ago",
    companyDescription: "CloudTech provides cloud infrastructure solutions for businesses of all sizes.",
    companyWebsite: "cloudtech.io",
    companyIndustry: "Cloud Computing",
    companySize: "50-100 employees",
  },
  {
    id: "5",
    title: "Product Manager",
    companyName: "ProductLabs",
    companyLogo: "/placeholder.svg?height=48&width=48",
    location: "Remote (US Only)",
    jobType: "Full-time",
    salary: "$120,000 - $150,000",
    experience: "4-6 years",
    description:
      "We're seeking a Product Manager to lead our product development efforts. You'll be responsible for defining product strategy and working with cross-functional teams to deliver exceptional products.",
    responsibilities: [
      "Define product vision, strategy, and roadmap",
      "Gather and prioritize product requirements",
      "Work with design and engineering teams to deliver features",
      "Analyze market trends and competitive landscape",
      "Track and measure product performance metrics",
    ],
    requirements: [
      "4+ years of experience in product management",
      "Experience working with software development teams",
      "Strong analytical and problem-solving skills",
      "Excellent communication and stakeholder management abilities",
      "Experience with agile methodologies",
    ],
    benefits: [
      "Competitive salary and equity",
      "Remote work flexibility",
      "Health, dental, and vision insurance",
      "401(k) with company match",
      "Professional development opportunities",
    ],
    skills: ["Product Strategy", "Agile", "User Research", "Data Analysis", "Roadmapping"],
    postedDate: "1 week ago",
    companyDescription: "ProductLabs builds innovative digital products that solve real-world problems.",
    companyWebsite: "productlabs.com",
    companyIndustry: "Product Development",
    companySize: "20-50 employees",
  },
  {
    id: "6",
    title: "Data Scientist",
    companyName: "DataInsights",
    companyLogo: "/placeholder.svg?height=48&width=48",
    location: "Remote (Worldwide)",
    jobType: "Full-time",
    salary: "$100,000 - $130,000",
    experience: "3-5 years",
    description:
      "We are looking for a Data Scientist to join our team. You'll be responsible for analyzing data, building machine learning models, and extracting insights to drive business decisions.",
    responsibilities: [
      "Analyze large datasets to identify patterns and trends",
      "Develop machine learning models to solve business problems",
      "Create data visualizations and reports",
      "Collaborate with engineering teams to implement models",
      "Stay up-to-date with the latest research and techniques",
    ],
    requirements: [
      "3+ years of experience in data science or related field",
      "Strong programming skills in Python",
      "Experience with machine learning libraries (scikit-learn, TensorFlow, PyTorch)",
      "Knowledge of SQL and data manipulation",
      "Experience with data visualization tools",
    ],
    benefits: [
      "Competitive salary",
      "Remote work",
      "Health insurance",
      "Flexible working hours",
      "Learning and development budget",
    ],
    skills: ["Python", "Machine Learning", "SQL", "Data Visualization", "Statistics"],
    postedDate: "2 weeks ago",
    companyDescription:
      "DataInsights helps businesses make data-driven decisions through advanced analytics and machine learning.",
    companyWebsite: "datainsights.ai",
    companyIndustry: "Data Analytics",
    companySize: "50-100 employees",
  },
]
