-- Insert sample blog posts
INSERT INTO blogs (title, excerpt, author, author_avatar, category, read_time, publish_date, image, featured, tags)
VALUES
  ('10 Tips for Landing Your First Remote Job',
   'Discover proven strategies to help you secure your first remote position in today''s competitive job market.',
   'Emma Rodriguez',
   '/placeholder.svg?height=40&width=40',
   'Career Advice',
   '5 min',
   '2023-05-10',
   '/placeholder.svg?height=200&width=350',
   true,
   ARRAY['Remote Work', 'Job Search', 'Career Tips']),
  ('The Future of Remote Work: Trends to Watch in 2023',
   'Explore emerging remote work trends that are shaping how companies and employees approach virtual collaboration.',
   'Michael Chen',
   '/placeholder.svg?height=40&width=40',
   'Industry Insights',
   '8 min',
   '2023-04-22',
   '/placeholder.svg?height=200&width=350',
   false,
   ARRAY['Remote Work', 'Future of Work', 'Workplace Trends']);

-- Insert sample internships
INSERT INTO internships (title, company, company_logo, location, duration, stipend, deadline, description, requirements, skills, featured)
VALUES
  ('Remote Software Engineering Intern',
   'TechCorp',
   '/placeholder.svg?height=48&width=48',
   'Remote (Worldwide)',
   '3 months',
   '$2000/month',
   '2023-06-30',
   'Join our engineering team to develop cutting-edge web applications using React and Node.js. You''ll work on real projects with experienced mentors.',
   ARRAY['Currently pursuing a degree in Computer Science or related field',
         'Knowledge of JavaScript, HTML, and CSS',
         'Basic understanding of React or similar frameworks',
         'Strong problem-solving skills'],
   ARRAY['JavaScript', 'React', 'Node.js', 'Git'],
   true),
  ('Digital Marketing Intern',
   'GrowthLabs',
   '/placeholder.svg?height=48&width=48',
   'Remote (US Only)',
   '6 months',
   '$1500/month',
   '2023-05-15',
   'Assist our marketing team in creating and implementing digital marketing campaigns. Gain hands-on experience with SEO, content marketing, and social media strategy.',
   ARRAY['Currently pursuing a degree in Marketing, Communications, or related field',
         'Strong writing and communication skills',
         'Basic understanding of SEO and social media platforms',
         'Creative mindset and attention to detail'],
   ARRAY['Content Marketing', 'SEO', 'Social Media', 'Analytics'],
   true);

-- Insert sample career events
INSERT INTO career_events (title, organizer, organizer_logo, type, format, start_date, end_date, price, description, topics, featured)
VALUES
  ('Full-Stack Web Development Bootcamp',
   'CodeAcademy',
   '/placeholder.svg?height=48&width=48',
   'bootcamp',
   'online',
   '2023-07-10',
   '2023-10-02',
   '$1,999',
   'Intensive 12-week bootcamp covering front-end and back-end development. Learn HTML, CSS, JavaScript, React, Node.js, and more. Build a portfolio of projects to showcase to employers.',
   ARRAY['HTML/CSS', 'JavaScript', 'React', 'Node.js', 'MongoDB', 'Express'],
   true),
  ('Remote Work Success Strategies',
   'Future of Work Institute',
   '/placeholder.svg?height=48&width=48',
   'seminar',
   'online',
   '2023-06-15',
   '2023-06-15',
   '$49',
   'A comprehensive seminar on thriving in remote work environments. Learn productivity techniques, communication strategies, and work-life balance tips from remote work experts.',
   ARRAY['Productivity', 'Communication', 'Work-Life Balance', 'Remote Tools'],
   true);

-- Insert sample job fairs
INSERT INTO job_fairs (title, organizer, organizer_logo, date, time, location, format, description, companies, registration_link, featured)
VALUES
  ('Global Remote Work Expo',
   'RemoteFirst Alliance',
   '/placeholder.svg?height=48&width=48',
   '2023-07-15',
   '9:00 AM - 5:00 PM EST',
   'Virtual Event',
   'online',
   'Connect with top remote-friendly companies from around the world. Attend workshops on remote job searching, interview preparation, and more.',
   ARRAY['TechCorp', 'InnovateSoft', 'DesignHub', 'CloudTech', 'DataInsights'],
   '#',
   true),
  ('Tech Careers Summit',
   'TechHire',
   '/placeholder.svg?height=48&width=48',
   '2023-08-05',
   '10:00 AM - 4:00 PM PST',
   'San Francisco Convention Center + Online',
   'hybrid',
   'The largest tech career fair on the West Coast. Meet recruiters from leading tech companies, attend tech talks, and network with industry professionals.',
   ARRAY['Google', 'Microsoft', 'Apple', 'Amazon', 'Meta', 'Salesforce'],
   '#',
   true);